-- =========================================================
-- SKILLMATCH - Ajustes PostgreSQL después de Psql_skillmatch.sql
-- Ejecutar conectado a la base skillmatch.
-- =========================================================

ALTER TABLE empresas
  ADD COLUMN IF NOT EXISTS estado VARCHAR(20) NOT NULL DEFAULT 'habilitada';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'chk_empresas_estado'
  ) THEN
    ALTER TABLE empresas
      ADD CONSTRAINT chk_empresas_estado
      CHECK (estado IN ('habilitada', 'deshabilitada'));
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS autenticadores_biometricos (
  id_credencial TEXT PRIMARY KEY,
  id_usuario INTEGER NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
  llave_publica BYTEA NOT NULL,
  contador BIGINT NOT NULL DEFAULT 0,
  fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_autenticadores_usuario
  ON autenticadores_biometricos(id_usuario);

CREATE TABLE IF NOT EXISTS vacantes (
  id_vacante INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_empresa INTEGER NOT NULL REFERENCES empresas(id_empresa) ON DELETE CASCADE,
  titulo VARCHAR(200) NOT NULL,
  categoria VARCHAR(100),
  nivel VARCHAR(100),
  descripcion TEXT,
  requisitos TEXT,
  estado VARCHAR(20) NOT NULL DEFAULT 'abierta'
    CHECK (estado IN ('abierta', 'cerrada', 'pausada')),
  fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_vacantes_empresa
  ON vacantes(id_empresa);

CREATE TABLE IF NOT EXISTS postulaciones (
  id_postulacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_vacante INTEGER NOT NULL REFERENCES vacantes(id_vacante) ON DELETE CASCADE,
  id_estudiante INTEGER NOT NULL REFERENCES estudiantes(id_estudiante) ON DELETE CASCADE,
  estado VARCHAR(30) NOT NULL DEFAULT 'pendiente'
    CHECK (estado IN ('pendiente', 'aceptada', 'rechazada', 'revisada')),
  fecha_postulacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_postulacion_estudiante_vacante UNIQUE (id_vacante, id_estudiante)
);

CREATE INDEX IF NOT EXISTS idx_postulaciones_estudiante
  ON postulaciones(id_estudiante);

CREATE TABLE IF NOT EXISTS proyecto_colaboradores (
  id_proyecto INTEGER NOT NULL REFERENCES proyectos(id_proyecto) ON DELETE CASCADE,
  id_estudiante INTEGER NOT NULL REFERENCES estudiantes(id_estudiante) ON DELETE CASCADE,
  fecha_registro TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id_proyecto, id_estudiante)
);

CREATE INDEX IF NOT EXISTS idx_proyecto_colaboradores_estudiante
  ON proyecto_colaboradores(id_estudiante);
