-- =========================================================
-- SKILLMATCH - Ajustes proyectos, multimedia, admin, vinculación y horarios
-- Ejecutar conectado a la base skillmatch.
-- =========================================================

BEGIN;

-- Empresas con datos del sistema académico: Nombre, RFC, domicilio y ubicación,
-- más datos del responsable que será el enlace ante la escuela.
ALTER TABLE empresas
  ADD COLUMN IF NOT EXISTS rfc VARCHAR(20),
  ADD COLUMN IF NOT EXISTS domicilio TEXT,
  ADD COLUMN IF NOT EXISTS ubicacion VARCHAR(180),
  ADD COLUMN IF NOT EXISTS sector VARCHAR(120),
  ADD COLUMN IF NOT EXISTS responsable_nombre VARCHAR(120),
  ADD COLUMN IF NOT EXISTS responsable_apellido VARCHAR(120),
  ADD COLUMN IF NOT EXISTS responsable_cargo VARCHAR(120),
  ADD COLUMN IF NOT EXISTS responsable_correo VARCHAR(180),
  ADD COLUMN IF NOT EXISTS responsable_telefono VARCHAR(40),
  ADD COLUMN IF NOT EXISTS observaciones TEXT,
  ADD COLUMN IF NOT EXISTS registrada_por INTEGER;

UPDATE empresas
SET estado = CASE
  WHEN estado IN ('activa','activo','aprobada') THEN 'habilitada'
  WHEN estado IN ('inactiva','inactivo','bloqueada') THEN 'deshabilitada'
  WHEN estado IS NULL OR TRIM(estado) = '' THEN 'pendiente'
  WHEN estado NOT IN ('pendiente', 'habilitada', 'deshabilitada', 'rechazada') THEN 'pendiente'
  ELSE estado
END;

ALTER TABLE empresas DROP CONSTRAINT IF EXISTS chk_empresas_estado;
ALTER TABLE empresas
  ADD CONSTRAINT chk_empresas_estado
  CHECK (estado IN ('pendiente', 'habilitada', 'deshabilitada', 'rechazada'));

CREATE UNIQUE INDEX IF NOT EXISTS uq_empresas_rfc_not_null
  ON empresas (UPPER(rfc))
  WHERE rfc IS NOT NULL AND TRIM(rfc) <> '';

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_empresas_registrada_por') THEN
    ALTER TABLE empresas
      ADD CONSTRAINT fk_empresas_registrada_por
      FOREIGN KEY (registrada_por) REFERENCES usuarios(id_usuario) ON DELETE SET NULL;
  END IF;
END $$;

-- Proyectos: campos faltantes y galería multimedia.
ALTER TABLE proyectos
  ADD COLUMN IF NOT EXISTS area_trabajo VARCHAR(150),
  ADD COLUMN IF NOT EXISTS ambito_desarrollo VARCHAR(180),
  ADD COLUMN IF NOT EXISTS es_innovacion INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ya_trabaja INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS competencia_impacto VARCHAR(80),
  ADD COLUMN IF NOT EXISTS objetivo TEXT,
  ADD COLUMN IF NOT EXISTS actividades TEXT,
  ADD COLUMN IF NOT EXISTS img_principal VARCHAR(500),
  ADD COLUMN IF NOT EXISTS tecnologias TEXT,
  ADD COLUMN IF NOT EXISTS id_profesor INTEGER;

ALTER TABLE proyectos ALTER COLUMN id_estudiante DROP NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_proyecto_profesor') THEN
    ALTER TABLE proyectos
      ADD CONSTRAINT fk_proyecto_profesor
      FOREIGN KEY (id_profesor) REFERENCES profesores(id_profesor) ON DELETE SET NULL;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_proyecto_autor') THEN
    ALTER TABLE proyectos
      ADD CONSTRAINT chk_proyecto_autor
      CHECK (id_estudiante IS NOT NULL OR id_profesor IS NOT NULL);
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS proyecto_media (
  id_media INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_proyecto INTEGER NOT NULL REFERENCES proyectos(id_proyecto) ON DELETE CASCADE,
  ruta_archivo VARCHAR(500) NOT NULL,
  tipo VARCHAR(20) NOT NULL DEFAULT 'imagen' CHECK (tipo IN ('imagen','video')),
  mime_type VARCHAR(120),
  nombre_original VARCHAR(255),
  orden INTEGER DEFAULT 1,
  fecha_subida TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_proyecto_media_proyecto ON proyecto_media(id_proyecto);

-- Horarios de profesores: aceptar PDF o imagen.
ALTER TABLE horarios_profesores
  ADD COLUMN IF NOT EXISTS titulo VARCHAR(180),
  ADD COLUMN IF NOT EXISTS descripcion TEXT,
  ADD COLUMN IF NOT EXISTS tipo_archivo VARCHAR(20) DEFAULT 'pdf';

-- Asegurar campos de perfil para suspensión/habilitación y fotos.
ALTER TABLE usuarios
  ADD COLUMN IF NOT EXISTS telefono VARCHAR(30),
  ADD COLUMN IF NOT EXISTS foto_perfil VARCHAR(255),
  ADD COLUMN IF NOT EXISTS fecha_registro DATE DEFAULT CURRENT_DATE;

ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS usuarios_estado_check;
ALTER TABLE usuarios
  ADD CONSTRAINT usuarios_estado_check
  CHECK (estado IN ('activo','inactivo'));

UPDATE usuarios SET fecha_registro = CURRENT_DATE WHERE fecha_registro IS NULL;

COMMIT;

SELECT 'Migración 07 aplicada correctamente' AS resultado;
