-- =========================================================
-- SKILLMATCH - Migracion 08 FIX
-- Habilidades blandas y busqueda robusta de alumnos.
-- Archivo en texto ASCII para evitar errores de encoding en Windows.
-- Ejecutar conectado a la base skillmatch.
-- =========================================================

BEGIN;

-- Permite quitar acentos en busquedas: Hernandez = Hernandez.
CREATE EXTENSION IF NOT EXISTS unaccent;

-- Nombre normalizado para busqueda.
ALTER TABLE usuarios
  ADD COLUMN IF NOT EXISTS nombre_busqueda TEXT;

CREATE OR REPLACE FUNCTION skillmatch_normalizar_nombre(valor TEXT)
RETURNS TEXT
LANGUAGE SQL
STABLE
AS $$
  SELECT regexp_replace(
    trim(
      regexp_replace(
        lower(public.unaccent(coalesce(valor, ''))),
        '\m(de|del|la|las|los|y)\M', ' ', 'g'
      )
    ),
    '\s+', ' ', 'g'
  );
$$;

CREATE OR REPLACE FUNCTION trg_usuarios_nombre_busqueda()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.nombre_busqueda := skillmatch_normalizar_nombre(
    coalesce(NEW.nombre, '') || ' ' || coalesce(NEW.apellido, '')
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS usuarios_nombre_busqueda_aiu ON usuarios;
CREATE TRIGGER usuarios_nombre_busqueda_aiu
BEFORE INSERT OR UPDATE OF nombre, apellido ON usuarios
FOR EACH ROW
EXECUTE FUNCTION trg_usuarios_nombre_busqueda();

UPDATE usuarios
SET nombre_busqueda = skillmatch_normalizar_nombre(
  coalesce(nombre, '') || ' ' || coalesce(apellido, '')
);

CREATE INDEX IF NOT EXISTS idx_usuarios_nombre_busqueda
  ON usuarios USING gin (to_tsvector('simple', coalesce(nombre_busqueda, '')));

-- Test de habilidades blandas tipo entrevista laboral.
CREATE TABLE IF NOT EXISTS soft_skills_preguntas (
  id_pregunta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  competencia VARCHAR(60) NOT NULL CHECK (competencia IN (
    'comunicacion',
    'trabajo_equipo',
    'liderazgo',
    'resolucion_problemas',
    'adaptabilidad',
    'profesionalismo'
  )),
  pregunta TEXT NOT NULL,
  orden INTEGER NOT NULL DEFAULT 1,
  activa BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS soft_skills_resultados (
  id_resultado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_estudiante INTEGER NOT NULL REFERENCES estudiantes(id_estudiante) ON DELETE CASCADE,
  puntaje_total INTEGER NOT NULL DEFAULT 0 CHECK (puntaje_total BETWEEN 0 AND 100),
  comunicacion INTEGER NOT NULL DEFAULT 0 CHECK (comunicacion BETWEEN 0 AND 100),
  trabajo_equipo INTEGER NOT NULL DEFAULT 0 CHECK (trabajo_equipo BETWEEN 0 AND 100),
  liderazgo INTEGER NOT NULL DEFAULT 0 CHECK (liderazgo BETWEEN 0 AND 100),
  resolucion_problemas INTEGER NOT NULL DEFAULT 0 CHECK (resolucion_problemas BETWEEN 0 AND 100),
  adaptabilidad INTEGER NOT NULL DEFAULT 0 CHECK (adaptabilidad BETWEEN 0 AND 100),
  profesionalismo INTEGER NOT NULL DEFAULT 0 CHECK (profesionalismo BETWEEN 0 AND 100),
  respuestas JSONB NOT NULL DEFAULT '[]'::jsonb,
  fecha_realizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_soft_skills_resultados_estudiante_fecha
  ON soft_skills_resultados(id_estudiante, fecha_realizacion DESC);

-- Semilla de preguntas. Escala: 1 nunca, 2 casi nunca, 3 a veces, 4 casi siempre, 5 siempre.
INSERT INTO soft_skills_preguntas (competencia, pregunta, orden, activa)
SELECT competencia, pregunta, orden, true
FROM (VALUES
  ('comunicacion', 'Cuando explico una idea tecnica, adapto mi lenguaje para que personas no tecnicas tambien me entiendan.', 1),
  ('comunicacion', 'Si no entiendo una instruccion, pregunto y confirmo antes de avanzar.', 2),
  ('trabajo_equipo', 'Cuando trabajo en equipo, comparto avances y aviso bloqueos a tiempo.', 3),
  ('trabajo_equipo', 'Acepto retroalimentacion y la uso para mejorar el resultado del proyecto.', 4),
  ('liderazgo', 'Puedo organizar tareas, priorizar pendientes y apoyar a otros sin esperar a que me lo pidan.', 5),
  ('liderazgo', 'Cuando hay desacuerdos, ayudo a mantener el enfoque en la solucion.', 6),
  ('resolucion_problemas', 'Ante un problema nuevo, analizo causas, propongo alternativas y valido la mejor opcion.', 7),
  ('resolucion_problemas', 'Documento lo que intente para que el equipo pueda entender y continuar el trabajo.', 8),
  ('adaptabilidad', 'Me adapto cuando cambian requisitos, herramientas o fechas de entrega.', 9),
  ('adaptabilidad', 'Aprendo herramientas nuevas cuando el proyecto lo requiere.', 10),
  ('profesionalismo', 'Cumplo compromisos, horarios y entregables aunque trabaje bajo presion.', 11),
  ('profesionalismo', 'Cuido la confidencialidad, la calidad y la presentacion de mi trabajo.', 12)
) AS seed(competencia, pregunta, orden)
WHERE NOT EXISTS (
  SELECT 1
  FROM soft_skills_preguntas p
  WHERE p.competencia = seed.competencia
    AND p.pregunta = seed.pregunta
);

COMMIT;

SELECT 'Migracion 08 aplicada correctamente' AS resultado;
