

-- SKILLMATCH - PostgreSQL

CREATE DATABASE Skillmatch;

-- TABLA ROLES
CREATE TABLE roles (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO roles (id_rol, nombre_rol) VALUES
(1,'admin'),
(2,'estudiante'),
(3,'empresa'),
(4,'profesor');


-- TABLA USUARIOS


CREATE TABLE usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    correo VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    id_rol INTEGER NOT NULL,
    estado VARCHAR(20) DEFAULT 'activo'
        CHECK (estado IN ('activo','inactivo')),

    CONSTRAINT fk_usuario_rol
        FOREIGN KEY (id_rol)
        REFERENCES roles(id_rol)
);

INSERT INTO usuarios VALUES
(
    3,
    'Oscar Daniel',
    'Mota Hernandez',
    '2024171013@uteq.edu.mx',
    '$2y$10$AC7.aM31gfT6xap0MYxVceEqY0P2CChuBdSlseKo9VXBh2kOO/Luy',
    2,
    'activo'
);


-- TABLA CARRERAS


CREATE TABLE carreras (
    id_carrera INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(150) NOT NULL
);

INSERT INTO carreras VALUES
(1,'Ing. en Desarrollo y Gestion de Software'),
(2,'Ing. Mecatronica'),
(3,'Ing. Ambiental'),
(4,'Ing. Redes');


-- TABLA ESTUDIANTES


CREATE TABLE estudiantes (
    id_estudiante INTEGER PRIMARY KEY,
    matricula VARCHAR(20) NOT NULL UNIQUE,
    carrera VARCHAR(100),
    semestre INTEGER,
    competencias TEXT,

    CONSTRAINT fk_estudiante_usuario
        FOREIGN KEY (id_estudiante)
        REFERENCES usuarios(id_usuario)
);

INSERT INTO estudiantes VALUES
(
    3,
    'MAT000003',
    'Ing. en Desarrollo y Gestión de Software',
    7,
    NULL
);


-- TABLA PROFESORES


CREATE TABLE profesores (
    id_profesor INTEGER PRIMARY KEY,
    departamento VARCHAR(100),
    asignaturas TEXT,

    CONSTRAINT fk_profesor_usuario
        FOREIGN KEY (id_profesor)
        REFERENCES usuarios(id_usuario)
);


-- TABLA EMPRESAS


CREATE TABLE empresas (
    id_empresa INTEGER PRIMARY KEY,
    razon_social VARCHAR(150) NOT NULL,
    giro VARCHAR(100),
    contacto VARCHAR(150),

    CONSTRAINT fk_empresa_usuario
        FOREIGN KEY (id_empresa)
        REFERENCES usuarios(id_usuario)
);


-- TABLA PROYECTOS


CREATE TABLE proyectos (
    id_proyecto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_estudiante INTEGER NOT NULL,

    titulo VARCHAR(200) NOT NULL,
    descripcion TEXT,

    fecha_registro DATE DEFAULT CURRENT_DATE,

    estado VARCHAR(20)
    DEFAULT 'en progreso'
    CHECK (
        estado IN (
            'en progreso',
            'completado',
            'pausado'
        )
    ),

    CONSTRAINT fk_proyecto_estudiante
        FOREIGN KEY (id_estudiante)
        REFERENCES estudiantes(id_estudiante)
);

INSERT INTO proyectos (
    id_proyecto,
    id_estudiante,
    titulo,
    descripcion,
    fecha_registro,
    estado
)
VALUES (
    6,
    3,
    'SkillMatch',
    'Página vinculada a la UTEQ',
    '2026-03-09',
    'en progreso'
);


-- TABLA EVIDENCIAS


CREATE TABLE evidencias (
    id_evidencia INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_proyecto INTEGER NOT NULL,

    ruta_archivo VARCHAR(255),
    tipo VARCHAR(50),

    fecha_subida TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_evidencia_proyecto
        FOREIGN KEY (id_proyecto)
        REFERENCES proyectos(id_proyecto)
);

INSERT INTO evidencias VALUES
(
    4,
    6,
    'uploads/evidencias/453f2e8c6c396d60235c92b3e8e651017d2e13574a433d46379acfff7ba4f03c.pdf',
    'manual|sha256:453f2e8c6c396d60235c92b3e8e651017d2e',
    '2026-03-10 00:42:44'
);

-- TABLA CVS


CREATE TABLE cvs (
    id_cv INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_estudiante INTEGER NOT NULL,

    ruta_pdf VARCHAR(255),

    fecha_generacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_cv_estudiante
        FOREIGN KEY (id_estudiante)
        REFERENCES estudiantes(id_estudiante)
);


-- TABLA CHATBOT


CREATE TABLE chatbot (
    id_pregunta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pregunta VARCHAR(255) NOT NULL,
    respuesta TEXT NOT NULL,
    categoria VARCHAR(50)
);


-- TABLA CALIFICACIONES


CREATE TABLE calificaciones (
    id_calificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_proyecto INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,

    puntaje NUMERIC(3,2),
    comentario TEXT,

    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_calificacion_proyecto
        FOREIGN KEY (id_proyecto)
        REFERENCES proyectos(id_proyecto),

    CONSTRAINT fk_calificacion_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios(id_usuario)
);


-- TABLA HORARIOS PROFESORES


CREATE TABLE horarios_profesores (
    id_horario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_profesor INTEGER NOT NULL,

    titulo VARCHAR(150) NOT NULL,
    descripcion TEXT,

    ruta_pdf VARCHAR(255) NOT NULL,

    fecha_subida TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_horario_profesor
        FOREIGN KEY (id_profesor)
        REFERENCES profesores(id_profesor)
);


-- TABLA AUDITORIA


CREATE TABLE auditoria (
    id_evento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    id_usuario INTEGER,

    accion VARCHAR(100),

    fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    ip_origen VARCHAR(50),

    CONSTRAINT fk_auditoria_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios(id_usuario)
);

INSERT INTO auditoria VALUES
(3,3,'REGISTRO','2026-03-09 20:33:57','::1'),
(4,3,'LOGIN','2026-03-09 20:50:46','::1'),
(5,3,'LOGIN','2026-03-09 20:57:24','::1'),
(6,3,'LOGIN','2026-03-09 20:58:21','::1'),
(7,3,'LOGIN','2026-03-09 21:08:19','::1'),
(8,3,'LOGIN','2026-03-09 23:50:35','::1'),
(9,3,'LOGIN','2026-03-13 02:51:35','::1'),
(10,3,'LOGIN','2026-03-13 20:34:00','::1');


-- ÍNDICES


CREATE INDEX idx_usuario_rol
ON usuarios(id_rol);

CREATE INDEX idx_proyecto_estudiante
ON proyectos(id_estudiante);

CREATE INDEX idx_evidencia_proyecto
ON evidencias(id_proyecto);

CREATE INDEX idx_cv_estudiante
ON cvs(id_estudiante);

CREATE INDEX idx_calificacion_proyecto
ON calificaciones(id_proyecto);

CREATE INDEX idx_calificacion_usuario
ON calificaciones(id_usuario);

CREATE INDEX idx_horario_profesor
ON horarios_profesores(id_profesor);

CREATE INDEX idx_auditoria_usuario
ON auditoria(id_usuario);


-- REINICIAR SECUENCIAS


SELECT setval(
    pg_get_serial_sequence('roles','id_rol'),
    COALESCE((SELECT MAX(id_rol) FROM roles),1)
);

SELECT setval(
    pg_get_serial_sequence('usuarios','id_usuario'),
    COALESCE((SELECT MAX(id_usuario) FROM usuarios),1)
);

SELECT setval(
    pg_get_serial_sequence('carreras','id_carrera'),
    COALESCE((SELECT MAX(id_carrera) FROM carreras),1)
);

SELECT setval(
    pg_get_serial_sequence('proyectos','id_proyecto'),
    COALESCE((SELECT MAX(id_proyecto) FROM proyectos),1)
);

SELECT setval(
    pg_get_serial_sequence('evidencias','id_evidencia'),
    COALESCE((SELECT MAX(id_evidencia) FROM evidencias),1)
);

SELECT setval(
    pg_get_serial_sequence('auditoria','id_evento'),
    COALESCE((SELECT MAX(id_evento) FROM auditoria),1)
);

